// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SixToFix.Infrastructure.Data;

#nullable disable

namespace SixToFix.Infrastructure.Migrations
{
    [DbContext(typeof(SixToFixDbContext))]
    [Migration("20260516041614_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_audits");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_audits_client_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audits_tenant_id");

                    b.ToTable("audits", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.AuditRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AiReadinessScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ai_readiness_score");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int?>("CompositeScore")
                        .HasColumnType("integer")
                        .HasColumnName("composite_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<Guid>("InitiatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by_user_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("SystemsMaturityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("systems_maturity_score");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tier")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_audit_runs");

                    b.HasIndex("AuditId")
                        .HasDatabaseName("ix_audit_runs_audit_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_audit_runs_tenant_id");

                    b.ToTable("audit_runs", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.BlobReference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("blob_name");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("container_name");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("LinkedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("linked_entity_id");

                    b.Property<string>("LinkedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("linked_entity_type");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_blob_references");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_blob_references_tenant_id");

                    b.HasIndex("LinkedEntityType", "LinkedEntityId")
                        .HasDatabaseName("ix_blob_references_linked_entity_type_linked_entity_id");

                    b.ToTable("blob_references", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.CalibrationDelta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("AdjustedActivityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("adjusted_activity_score");

                    b.Property<string>("AdjustedDocumentedStrategy")
                        .HasColumnType("text")
                        .HasColumnName("adjusted_documented_strategy");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_run_id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<decimal>("OriginalActivityScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("original_activity_score");

                    b.Property<string>("OriginalDocumentedStrategy")
                        .HasColumnType("text")
                        .HasColumnName("original_documented_strategy");

                    b.Property<string>("OverrideReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("override_reason_code");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_calibration_deltas");

                    b.HasIndex("AuditRunId")
                        .HasDatabaseName("ix_calibration_deltas_audit_run_id");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_calibration_deltas_tenant_id_id");

                    b.ToTable("calibration_deltas", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.CategoryConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuditId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomPromptOverride")
                        .HasColumnType("text")
                        .HasColumnName("custom_prompt_override");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_category_configs");

                    b.HasIndex("AuditId")
                        .HasDatabaseName("ix_category_configs_audit_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_category_configs_tenant_id");

                    b.HasIndex("AuditId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ix_category_configs_audit_id_category");

                    b.ToTable("category_configs", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.CategoryResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("activity_score");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_run_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text")
                        .HasColumnName("review_notes");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("SystemsMaturityContribution")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("systems_maturity_contribution");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_category_results");

                    b.HasIndex("AuditRunId")
                        .HasDatabaseName("ix_category_results_audit_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_category_results_tenant_id");

                    b.HasIndex("AuditRunId", "Category")
                        .IsUnique()
                        .HasDatabaseName("ix_category_results_audit_run_id_category");

                    b.ToTable("category_results", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.CategoryResultVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<int>("ActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("activity_score");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("CategoryResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_result_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text")
                        .HasColumnName("review_notes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_category_result_versions");

                    b.HasIndex("CategoryResultId")
                        .HasDatabaseName("ix_category_result_versions_category_result_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_category_result_versions_tenant_id");

                    b.HasIndex("CategoryResultId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_category_result_versions_category_result_id_version");

                    b.ToTable("category_result_versions", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("HubSpotCompanyId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hub_spot_company_id");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasIndex("HubSpotCompanyId")
                        .HasDatabaseName("ix_clients_hub_spot_company_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_clients_tenant_id");

                    b.HasIndex("TenantId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_tenant_id_slug");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.CouncilSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AdjustedScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("adjusted_score");

                    b.Property<string>("AdvocateOutputJson")
                        .HasColumnType("text")
                        .HasColumnName("advocate_output_json");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("decision");

                    b.Property<string>("JudgeOutputJson")
                        .HasColumnType("text")
                        .HasColumnName("judge_output_json");

                    b.Property<string>("Rationale")
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.Property<string>("SkepticOutputJson")
                        .HasColumnType("text")
                        .HasColumnName("skeptic_output_json");

                    b.Property<Guid>("SkillRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_council_sessions");

                    b.HasIndex("SkillRunId")
                        .HasDatabaseName("ix_council_sessions_skill_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_council_sessions_tenant_id");

                    b.ToTable("council_sessions", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.HubSpotSyncQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_retry_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_hub_spot_sync_queue");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_hub_spot_sync_queue_client_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_hub_spot_sync_queue_tenant_id");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("ix_hub_spot_sync_queue_status_next_retry_at");

                    b.ToTable("hub_spot_sync_queue", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConfigJson")
                        .HasColumnType("text")
                        .HasColumnName("config_json");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_code");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("severity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_policies");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_policies_tenant_id");

                    b.HasIndex("TenantId", "RuleCode")
                        .IsUnique()
                        .HasDatabaseName("ix_policies_tenant_id_rule_code");

                    b.ToTable("policies", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.PolicyFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Detail")
                        .HasColumnType("text")
                        .HasColumnName("detail");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_code");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("severity");

                    b.Property<Guid>("SkillRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_run_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_policy_flags");

                    b.HasIndex("SkillRunId")
                        .HasDatabaseName("ix_policy_flags_skill_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_policy_flags_tenant_id");

                    b.ToTable("policy_flags", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.ReviewerAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_run_id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_reviewer_actions");

                    b.HasIndex("AuditRunId")
                        .HasDatabaseName("ix_reviewer_actions_audit_run_id");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_reviewer_actions_tenant_id_id");

                    b.ToTable("reviewer_actions", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.ReviewerLockout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_run_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<int>("RejectionCount")
                        .HasColumnType("integer")
                        .HasColumnName("rejection_count");

                    b.Property<Guid>("ReviewerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_user_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("WindowStartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_started_at");

                    b.HasKey("Id")
                        .HasName("pk_reviewer_lockouts");

                    b.HasIndex("AuditRunId")
                        .HasDatabaseName("ix_reviewer_lockouts_audit_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_reviewer_lockouts_tenant_id");

                    b.HasIndex("TenantId", "AuditRunId", "Category", "ReviewerUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_reviewer_lockouts_tenant_id_audit_run_id_category_reviewer_");

                    b.ToTable("reviewer_lockouts", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.SkillRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ActivityScore")
                        .HasColumnType("integer")
                        .HasColumnName("activity_score");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_run_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("InputBlobReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("input_blob_reference");

                    b.Property<string>("OutputBlobReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("output_blob_reference");

                    b.Property<int>("SequenceIndex")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_index");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skill_name");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_skill_runs");

                    b.HasIndex("AuditRunId")
                        .HasDatabaseName("ix_skill_runs_audit_run_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_skill_runs_tenant_id");

                    b.ToTable("skill_runs", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.TelemetryEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("audit_run_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CouncilRunCount")
                        .HasColumnType("integer")
                        .HasColumnName("council_run_count");

                    b.Property<DateTimeOffset>("InitializedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("initialized_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("PolicyTriggerCount")
                        .HasColumnType("integer")
                        .HasColumnName("policy_trigger_count");

                    b.Property<int>("ReviewerActionCount")
                        .HasColumnType("integer")
                        .HasColumnName("reviewer_action_count");

                    b.Property<int>("SkillRunCount")
                        .HasColumnType("integer")
                        .HasColumnName("skill_run_count");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("total_latency_ms");

                    b.Property<int>("TotalTokensUsed")
                        .HasColumnType("integer")
                        .HasColumnName("total_tokens_used");

                    b.HasKey("Id")
                        .HasName("pk_telemetry_events");

                    b.HasIndex("AuditRunId")
                        .IsUnique()
                        .HasDatabaseName("ix_telemetry_events_audit_run_id");

                    b.HasIndex("TenantId", "Id")
                        .HasDatabaseName("ix_telemetry_events_tenant_id_id");

                    b.ToTable("telemetry_events", (string)null);
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_slug");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("SixToFix.Infrastructure.Auth.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TenantSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenant_slug");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SixToFix.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SixToFix.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("SixToFix.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SixToFix.Infrastructure.Auth.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.Audit", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.Client", "Client")
                        .WithMany("Audits")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audits_clients_client_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Audits")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audits_tenants_tenant_id");

                    b.Navigation("Client");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.AuditRun", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.Audit", "Audit")
                        .WithMany("AuditRuns")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_audit_runs_audits_audit_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_runs_tenants_tenant_id");

                    b.Navigation("Audit");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.BlobReference", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_blob_references_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.CalibrationDelta", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany()
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calibration_deltas_audit_runs_audit_run_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_calibration_deltas_tenants_tenant_id");

                    b.Navigation("AuditRun");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.CategoryConfig", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.Audit", "Audit")
                        .WithMany("CategoryConfigs")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_configs_audits_audit_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_configs_tenants_tenant_id");

                    b.Navigation("Audit");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.CategoryResult", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany("CategoryResults")
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_results_audit_runs_audit_run_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_results_tenants_tenant_id");

                    b.Navigation("AuditRun");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.CategoryResultVersion", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.CategoryResult", "CategoryResult")
                        .WithMany("Versions")
                        .HasForeignKey("CategoryResultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_result_versions_category_results_category_result_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_result_versions_tenants_tenant_id");

                    b.Navigation("CategoryResult");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.Client", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Clients")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clients_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.CouncilSession", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.SkillRun", "SkillRun")
                        .WithMany()
                        .HasForeignKey("SkillRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_council_sessions_skill_runs_skill_run_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_council_sessions_tenants_tenant_id");

                    b.Navigation("SkillRun");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.HubSpotSyncQueue", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_hub_spot_sync_queue_clients_client_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_hub_spot_sync_queue_tenants_tenant_id");

                    b.Navigation("Client");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.Policy", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policies_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.PolicyFlag", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.SkillRun", "SkillRun")
                        .WithMany("PolicyFlags")
                        .HasForeignKey("SkillRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_policy_flags_skill_runs_skill_run_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_policy_flags_tenants_tenant_id");

                    b.Navigation("SkillRun");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.ReviewerAction", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany()
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviewer_actions_audit_runs_audit_run_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviewer_actions_tenants_tenant_id");

                    b.Navigation("AuditRun");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.ReviewerLockout", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany()
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reviewer_lockouts_audit_runs_audit_run_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reviewer_lockouts_tenants_tenant_id");

                    b.Navigation("AuditRun");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.SkillRun", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany("SkillRuns")
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_runs_audit_runs_audit_run_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_skill_runs_tenants_tenant_id");

                    b.Navigation("AuditRun");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.TelemetryEvent", b =>
                {
                    b.HasOne("SixToFix.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany()
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telemetry_events_audit_runs_audit_run_id");

                    b.HasOne("SixToFix.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_telemetry_events_tenants_tenant_id");

                    b.Navigation("AuditRun");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.Audit", b =>
                {
                    b.Navigation("AuditRuns");

                    b.Navigation("CategoryConfigs");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.AuditRun", b =>
                {
                    b.Navigation("CategoryResults");

                    b.Navigation("SkillRuns");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.CategoryResult", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.Client", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.SkillRun", b =>
                {
                    b.Navigation("PolicyFlags");
                });

            modelBuilder.Entity("SixToFix.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Audits");

                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
